use_frameworks!

platform :ios, '8.0'

target 'SDWebImageMapKitPlugin_Example' do
  pod 'SDWebImageMapKitPlugin', :path => '../'

  target 'SDWebImageMapKitPlugin_Tests' do
    inherit! :search_paths

    
  end
end
